server:
  port: ${PORT:0}
spring:
  application:
    name: ${rootArtifactId}-ms-et
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8085/auth/realms/startupframework/protocol/openid-connect/certs
eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
